const { gql } = require('apollo-server');

module.exports = gql`

type Product {
  id: ID
  name: String,
  year: String,
  unitProductSold: Int,
  unitSalePrice: Int,
  stock: Int
  turnoverProduct: Int
  category: String
  status: String
  delivery: Int
  omSite: Int
} 

enum STATUS {
  draft
  Published
}
enum CATEGORY {
  drink
  food
  other
}
input CreateProduct {
  name: String,
  unitSalePrice: Int,
  category: CATEGORY
} 
input UpdateProduct {
  name: String,
  unitSalePrice: Int,
  status: STATUS
  category: CATEGORY
} 
input SoldProduct {
  unitProductSold: Int, 
} 

type Mutation {
  createProduct(restaurantId: String!, createProductInput: CreateProduct ): Restaurant
  updateProduct(restaurantId : ID!, productId: ID!, updateProductInput: UpdateProduct): Restaurant
  soldProduct(restaurantId : ID!, productId: ID!, soldProductInput: SoldProduct): Restaurant
  deleteProduct(restaurantId: ID!, productId: ID! ): Restaurant
}`;
