const { gql } = require('apollo-server');

module.exports = gql`
type Restaurant {
  id: ID 
  name: String
  description: String
  address: String
  city: String
  country: String
  create_at: String
  status: String
  admin: [User!]
  employees: [Employee]!
  products: [Product]!
  turnoversYears: [Turnover]!
} 
type Employee {
  id: ID
  firstname: String
  lastname: String
  role: String
  salary: Int
  admin: String
} 
type Turnover {
  id: ID
  year: String,
  total: Int,
} 
input CreateRestaurant {
  name: String
  description: String
  address: String
  city: String
  country: String
  status: STATUS
}
enum STATUS {
  new
  progress
  completed
}
input CreateEmployee {
  firstname: String
  lastname: String
  role: String
  salary: String
} 

type Query {
  getRestaurant(restaurantId : ID!): Restaurant
  getRestaurants: [Restaurant]
}
type Mutation {
  createRestaurant(createRestaurantInput: CreateRestaurant): Restaurant!
  deleteRestaurant(restaurantId: ID!): Restaurant
  createEmployee(restaurantId: String!, createEmployeeInput: CreateEmployee ): Restaurant
  deleteEmployee(restaurantId: ID!, employeeId: ID! ): Restaurant

  updateRestaurant(restaurantId : ID!, createRestaurantInput: CreateRestaurant): Restaurant
}`;
