FROM node

WORKDIR /home/node/app

COPY package.json package-lock.json ./

RUN npm install

COPY . ./
# COPY config ./config
# COPY graphql ./graphql
# COPY models ./models
# COPY util ./util
EXPOSE 4010

# start app
CMD ["npm", "run", "docker"]
